### ISSUE TITLE
ERROR: Failed to find 'typescript' module. Please check, NODE_PATH contains location of global 'typescript' or install locally in your project

### ISSUE THREAD

**Issue by phBalance** [SonarSource/sonar-scanner-cli-docker#103]
Hi,
   when trying to run a scan against TypeScript files, it produces the following error `ERROR: Failed to find 'typescript' module. Please check, NODE_PATH contains location of global 'typescript' or install locally in your project` when using the latest from https://hub.docker.com/r/sonarsource/sonar-scanner-cli. Looking back through the tagged releases at https://hub.docker.com/r/sonarsource/sonar-scanner-cli/tags?page=1&ordering=last_updated, 4.4 seems to have a valid `NODE_PATH` but 4.5 and 4.6 do not.

```sh
$ docker image ls | grep sonar
sonarsource/sonar-scanner-cli         latest               05fee3dc9a56        36 hours ago        357MB
```

I see this same problem has been previously reported as #102, but after posting the workaround that person just closed the issue. Looking a little closer it appears that the docker image is not setup correctly given the TypeScript module is installed in the image. 

https://github.com/SonarSource/sonar-scanner-cli-docker/blob/014764f6741b8ce2551434e92d611f74154b0e54/4/Dockerfile#L31

```sh
# docker run --rm   -it sonarsource/sonar-scanner-cli:latest /bin/bash 
bash-5.0# echo $NODE_PATH
/lib/node_modules

bash-5.0# ls $NODE_PATH
ls: /lib/node_modules: No such file or directory

bash-5.0# ls -l /usr/lib/node_modules/
total 8
drwxr-xr-x    8 root     root          4096 Mar 30 03:34 npm
drwxr-xr-x    5 root     root          4096 Mar 30 03:34 typescript

bash-5.0# echo $PATH
/opt/java/openjdk/bin:/opt/sonar-scanner/bin:/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

bash-5.0# which node
/usr/bin/node
```

A closer look at https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/Dockerfile show that `NODE_PATH`and `PATH` are setup at https://github.com/SonarSource/sonar-scanner-cli-docker/blob/014764f6741b8ce2551434e92d611f74154b0e54/4/Dockerfile#L12-L13

I can't see where `NODEJS_HOME` is being set in the repo, but if I had to guess this was empty/not set given the produced `NODE_PATH` and `PATH` environment variables. Setting `NODE_PATH` to `/usr/lib/node_modules` fixes the issue.

Thanks!

**Comment by jhpedemonte** [comment]
I'm running into the same issue. `NODEJS_HOME` needs to be defined.

**Comment by jhpedemonte** [comment]
Latest image (published around same time that PR was merged) still lists `NODE_PATH`. Will a new image be built?

![Screen Shot 2021-05-12 at 11 08 00 AM](https://user-images.githubusercontent.com/711365/118008041-52828200-b312-11eb-822a-6493e6e817b5.png)

**Comment by tobias-trabelsi-sonarsource** [comment]
yeah sorry for that. there was another release that updated the embedded jre in the parent project (sonar-scanner-cli) and the PR was merged after the release was done. i will clarify if we just push the changes done here to the docker hub or if we need to create a new release for that.
thanks for pointing this out @jhpedemonte

**Comment by wouter-admiraal-sonarsource** [comment]
So, this seems to have been introduced by this commit: https://github.com/SonarSource/sonar-scanner-cli-docker/commit/948d0d9bafc715f8fb1cf4fc4f7c91e8d2edaa2a

Thanks for the report @jhpedemonte. We'll fix this ASAP.

**Comment by wouter-admiraal-sonarsource** [comment]
This is tracked by https://jira.sonarsource.com/browse/SQSCANNER-90. We will fix it ASAP.

**Comment by wouter-admiraal-sonarsource** [comment]
PR here: https://github.com/SonarSource/sonar-scanner-cli-docker/pull/106
