### ISSUE TITLE
Difference in Compatibility Warning (README.md <-> Docker Hub)

### ISSUE THREAD

**Issue by Crayjin** [SonarSource/sonar-scanner-cli-docker#109]
Hi there,

just a small issue:

The README.md says the following: 

"NB: These Docker images are not compatible with C/C#/C++/Objective-C projects."

but the Docker Hub website (https://hub.docker.com/r/sonarsource/sonar-scanner-cli) says 

"Warning: These Docker images are not compatible with C/C++/Objective-C projects."

which is missing C#.

I guess it's important to update one of the pages to make sure nobody is wasting their and potentially your time. :-)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hey @Crayjin ,

thanks for pointing this out. this will be tracked with [SQSCANNER-91](https://jira.sonarsource.com/browse/SQSCANNER-91) and fixed soon :)
