### ISSUE TITLE
Sonar Scanner Docker Image with dotnet core scanner

### ISSUE THREAD

**Issue by olavorn** [SonarSource/sonar-scanner-cli-docker#116]
In order to run .net core apps in this ci/cd pipeline, it is necessary to install java in a [DotNet SDK image](https://hub.docker.com/_/microsoft-dotnet) or to install DotNet SDK into a Java Image or in this scanner cli image. 

Since in my company we use Red Hat openshift, SonarSource could provide an image in order to run as [sonarscanner-for-msbuild](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/) in a docker image. It would be much simpler to setup in ci-cd environments. 

I sense [this image](
`burakince/docker-dotnet-sonarscanner`) is almost what I want, but this image targets .net 2.2, and there should be other targets.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @olavorn ,

the link you posted results in a 404.
anyway this seems like a feature request to me as it's stated in the `README.md` of this project that
>These Docker images are not compatible with C/C#/C++/Objective-C projects.

please raise your issues in the "[suggest new features](https://community.sonarsource.com/c/suggestions/12)" category of our [community forum](https://community.sonarsource.com/)

**Comment by olavorn** [comment]
Whatever, I did it myself. 

https://hub.docker.com/repository/docker/olavorn/docker-dotnet-31-sonarscanner

It does the job.
