### ISSUE TITLE
[Request] upgrade typescript to v4 and nodejs to v14

### ISSUE THREAD

**Issue by e-cloud** [SonarSource/sonar-scanner-cli-docker#117]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

the current node.js lts is v14, and latest sonarqube server support typescript v4

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @e-cloud ,

can you confirm the node version in the latest image? i tested it locally and node is already at v14 

```bash
docker run -it --rm --pull always --entrypoint=/bin/bash sonarsource/sonar-scanner-cli:4.6
4.6: Pulling from sonarsource/sonar-scanner-cli
Digest: sha256:74248aad66a9083516bf2c1d31a1737e0cb0959a190f4c2086ec3c053f59600b
Status: Downloaded newer image for sonarsource/sonar-scanner-cli:4.6
bash-5.1# node --version
v14.17.6
```

**Comment by e-cloud** [comment]
yap, it's v14 with the latest one, but the source

https://github.com/SonarSource/sonar-scanner-cli-docker/blob/57ffa73426b01e3f7683e4831509f531f74f5a96/4/Dockerfile#L22

is noted as 10, which is a little bit confusing.

**Comment by tobias-trabelsi-sonarsource** [comment]
it is noted as bigger than 10
