### ISSUE TITLE
Upgrade to newest Typescript-Version possible?

### ISSUE THREAD

**Issue by schlundus** [SonarSource/sonar-scanner-cli-docker#118]
Currently Typescript 3.7.5 is used during scan, which is a little bit outdated.
`   && npm install -g typescript@3.7.5 \`

Is it somehow possible to upgrade tor overwrite the version to be used during scanning?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @schlundus ,

thanks for the ping. after a discussion with the team that develops the js/ts analyzer we concluded that we want to remove typescript from this docker image as there is a typescript installation embedded into the analyzer itself (https://github.com/SonarSource/SonarJS/issues/2010)

**Comment by tobias-trabelsi-sonarsource** [comment]
hi @babusatti ,

please open a thread in our [community forum](https://community.sonarsource.com/) and also note that SQ 8.5 is EOL. you should update to at least the current LTS (8.9) or the latest release of SQ (9.3 as of writing)
