### ISSUE TITLE
Update Browserslist automatically

### ISSUE THREAD

**Issue by marcommonokee** [SonarSource/sonar-scanner-cli-docker#122]
Hello there, there is an issue in the latest image of sonar-scanner-cli-docker concerning `Browserslist` that make the scan unsuccessful.

```
ERROR: Browserslist: caniuse-lite is outdated. Please run:
ERROR: npx browserslist@latest --update-db
ERROR: 
ERROR: Why you should do it regularly:
ERROR: https://github.com/browserslist/browserslist#browsers-data-updating
```

Is it possible to automate such update either inside the entry point or in the way you generate the images?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @marcommonokee ,

This error message is not directly generated by the sonar-scanner-cli image but rather coming from the js/css language plugin and is tracked with https://github.com/SonarSource/sonar-css/issues/370 and https://github.com/SonarSource/SonarJS/issues/2803 .

as stated in these issues you can set the environment variable `BROWSERSLIST_IGNORE_OLD_DATA`  to `true` to avoid this
