### ISSUE TITLE
Base image incompatible with build-wrapper

### ISSUE THREAD

**Issue by sguarin** [SonarSource/sonar-scanner-cli-docker#123]
Base image used is:
```
FROM alpine:3.14
```
When using alpine:3.14.2 build-wrapper can be installed and used in sonar-scanner-cli image.
When using alpine:3.14.3 it throws the following error:
```
apk add curl gcompat
curl -o /tmp/build-wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
unzip /tmp/build-wrapper.zip
./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --help
Error relocating /usr/src/build-wrapper-linux-x86/build-wrapper-linux-x86-64: getwd: symbol not found
```

Is not a sonar-scanner-cli specific issue, but it would be very usefull to use build-wrapper on top of sonar-scanner-cli-docker image.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @sguarin ,

this is a glibc / musllibc incompatibility. i will raise this point internally and continue to track this with https://jira.sonarsource.com/browse/DOCKER-57 if there are plans to support the build wrapper on musllibc based systems but as of now i can only state again that the sonar-scanner-cli docker image is not intended to be used with languages from the c family
