### ISSUE TITLE
NB: These Docker images are not compatible with C/C#/C++/Objective-C projects.

### ISSUE THREAD

**Issue by romanek-adam** [SonarSource/sonar-scanner-cli-docker#132]
Could you please explain why README.md mentions:

> NB: These Docker images are not compatible with C/C#/C++/Objective-C projects.

I need support for C++ so it would be good to know what the problem is.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @romanek-adam ,

>The Build Wrapper collects information about the build including absolute file paths (source files, standard headers, libraries, etc...). Later on, SonarScanner uses this information and needs to access those paths. Whereas this is straightforward while running these 2 steps on the same host, it is worth some consideration when using any sort of containerization. A consequence of this is that C / C++ / Objective-C analysis is NOT supported by [SonarScanner CLI Docker image](https://hub.docker.com/r/sonarsource/sonar-scanner-cli).

from: https://docs.sonarqube.org/latest/analysis/languages/cfamily/ 

if you have any other questions feel free to create a new thread in our [community forum](https://community.sonarsource.com/)
