### ISSUE TITLE
Found Vulnerability for sonarsource/sonar-scanner-cli:4.7

### ISSUE THREAD

**Issue by mhinojosac** [SonarSource/sonar-scanner-cli-docker#152]
Hello, we're using your latest version of sonarsource/sonar-scanner-cli:4.7 and we noticed that you have a vulnerability with the com.squareup.okhttp3_okhttp package (PRISMA-2022-0239). This vulnerability is fixed as of version 4.9.2. Do you plan to upgrade this version in future releases?

Log of the scan tool:
_com.squareup.okhttp3_okhttp packages prior to version 4.9.2 are vulnerable for sensitive information disclosure. An illegal character in a header value will cause IllegalArgumentException which will include full header value. This applies to Authorization, Cookie, Proxy-Authorization and Set-Cookie headers_

**Comment by jCOTINEAU** [comment]
Hello @mhinojosac thanks a lot for taking the time to participate in the community.

The Docker image is just a shell to run the [sonar-scanner-cli ](https://github.com/SonarSource/sonar-scanner-cli) binary.

I suggest you to open a ticket on the proper community forum [here](https://community.sonarsource.com/), it will be picked by the whole Dev team.

Regards, let me know if that issue can be closed.
