### ISSUE TITLE
Build for arm

### ISSUE THREAD

**Issue by imcdo** [SonarSource/sonar-scanner-cli-docker#184]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs
Can we build this image for arm platforms as well?  In general this will improve usability on arm platforms as execution will be much better.

**Comment by jCOTINEAU** [comment]
Hello @imcdo, we do have plan for providing ARM64 images for the sonar-scanner-cli-docker, Nonetheless i can not give you a specific date, as this is not yet prioritized.

Regards,
jeremy.
