### ISSUE TITLE
Only .json format of golang test report paths works

### ISSUE THREAD

**Issue by mqw** [SonarSource/sonar-scanner-cli-docker#185]
I try to include test reports by 
`sonar.go.tests.reportPaths=jenkins/result/WM.json,jenkins/result/COMMON.txt,jenkins/result/*.txt,jenkins/result/**/*.txt,jenkins/result/*.json,jenkins/result/**/*.json`
There are files matching all the paths but the only one working actually included is jenkins/result/WM.json

```
00:55:09  INFO: Sensor Go Unit Test Report [go]
00:55:09  ERROR: Test report can't be loaded, file not found: '/local-store/workspace/workspace/Workflow_testing123/jenkins/result/*.txt', ignoring this file.
00:55:09  ERROR: Test report can't be loaded, file not found: '/local-store/workspace/workspace/Workflow_testing123/jenkins/result/**/*.txt', ignoring this file.
00:55:09  ERROR: Test report can't be loaded, file not found: '/local-store/workspace/workspace/Workflow_testing123/jenkins/result/*.json', ignoring this file.
00:55:09  ERROR: Test report can't be loaded, file not found: '/local-store/workspace/workspace/Workflow_testing123/jenkins/result/**/*.json', ignoring this file.
00:55:09  INFO: Sensor Go Unit Test Report [go] (done) | time=73ms

**Comment by jCOTINEAU** [comment]
hello @mqw, thanks a lot for taking the time to participate in the community.

Could you please try with the sonar-scanner-cli zip and not the docker image ? 

The docker image is a shell around the sonar-scanner-cli zip, based on that the issue you have might be related to the code and not the docker image.

In such cases i would suggest you to open a ticket on our community forum [here](https://community.sonarsource.com/)

Regards,
Jérémy
