### ISSUE TITLE
Deprecate sonar.login and sonar.password

### ISSUE THREAD

**Issue by dirsigler** [SonarSource/sonar-scanner-cli-docker#187]
Please ensure your issue adheres to the following guidelines: 
- [X] Please check the problem is not already reported
- [X] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

The docker image still uses `sonar.login` and `sonar.token` even tho both properties are subject to be deprecated.
It would make sense to utilise already the new primary approach of `sonar.token`.

**Comment by jCOTINEAU** [comment]
Hello @dirsigler, thanks a lot for taking the time to participate in the community.

Could you please elaborate a bit? The docker image does not use anything as is, it is up to the user to configure how to use it at runtime.

Do you mean that the documentation is not up to date and should better reflect that deprecation policy ?

**Comment by dirsigler** [comment]
Hey,

it's about the entrypoint.sh:
https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/bin/entrypoint.sh#L34-L35

**Comment by jCOTINEAU** [comment]
You are right, this is the historical compatibility script, it will be removed soon when we move to the new eclipse-temurin base image.

keeping the issue to track it, will provide more details on the public tickets soon

**Comment by davividal** [comment]
Hi, @dirsigler.

The script was updated, and we are now using `sonar.token`!

Thank you for your feedback!

**Comment by dirsigler** [comment]
Thank you all 🚀 !
