### ISSUE TITLE
Providing linux/arm64 image on hub.docker.com

### ISSUE THREAD

**Issue by mhoeper** [SonarSource/sonar-scanner-cli-docker#197]
The current sonar-scanner-cli-docker works with linux/arm64, I can build that locally, however, on hub.docker.com, there are only images available for linux/amd64. 

Going forward, can you please push images for linux/arm64, too?

**Comment by jCOTINEAU** [comment]
Hello @mhoeper, thanks a lot for participating in the community.

The ARM64 for sonar-scanner-cli-docker is an ongoing topic that we are pushing for. Nonetheless, it requires a huge validation as we thrive for quality and would like to make sure that every language scanned behaves as expected with ARM64.

I will close this issue if that's fine with you, stay tuned on sonar media for more information.
