### ISSUE TITLE
Push docker image to other public registries

### ISSUE THREAD

**Issue by larivierec** [SonarSource/sonar-scanner-cli-docker#203]
Public registries

- ghcr.io
- public.ecr.aws

Would it be possible to push this docker image to other public registries?
Usually, this doesn't involve much work, I could suggest a PR however, i'm not sure if there are repercussions as that would require I have access to secrets.

docker.io limits quite quickly on "Too Many Requests HTTP 429"

**Comment by carminevassallo** [comment]
Hi @larivierec,

Thanks for reporting this feature request! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

If you think this request is still relevant, could you please post it there? In the meantime, I'm closing it.

**Comment by larivierec** [comment]
gotcha will do, it's actually posted here.
https://community.sonarsource.com/t/build-push-docker-image-to-ghcr-io/89745

i'll comment on it
