### ISSUE TITLE
Docker images built for multiple platforms, eg. LINUX/ARM64

### ISSUE THREAD

**Issue by mkarwin** [SonarSource/sonar-scanner-cli-docker#205]
Currently you're publishing the image with Sonar Scanner CLI in docker format for linux/amd64 only.
Bearing in mind high proliferation of ARM ecosystem devices in server space, there are many builds happening on ARM nodes. Currently, in most CI/CD solutions this leads to needing to build on one node for target architecture, but scan only on x86 as the container provided by SonarSource is released solely in linux/amd64 variant. Can you produce scanner images for linux/arm64 platform as well? This would reduce the complexity of infra and workloads on CI/CD devops teams of your customers as then they could re-use your image for both x86 and ARM builds alike.

**Comment by mkarwin** [comment]
Please be aware that your dockerfile and CLI itself is basically platform indepedent, the build however uses a basic docker build tooling in https://github.com/SonarSource/sonar-scanner-cli-docker/blob/5d6704a2588e581e417895717bd999cbd18620fe/.github/workflows/release.yml#L44 but instead you could be using GitHub's provided docker/build-push-action@v4 wherein you could provide multiplatform option to build using buildx and as a result produce both amd64 and arm64 target architectures relatively easily.

**Comment by RodrigoDornelles** [comment]
can be worked on cross-platform using buildx!

 * <https://docs.docker.com/build/building/multi-platform/>
 * <https://github.com/marketplace/actions/docker-setup-qemu>
 * <https://github.com/marketplace/actions/docker-setup-buildx>
 * <https://github.com/marketplace/actions/docker-login>
 * <https://github.com/marketplace/actions/build-and-push-docker-images>

**Comment by jCOTINEAU** [comment]
Hello everyone, this is a recurring topic that is raised as issues.

The ARM64 for [sonar-scanner-cli-docker](https://sonarsource.atlassian.net/browse/SONAR-scanner-cli-docker) is an ongoing topic that we are pushing for. Nonetheless, it requires a huge validation as we thrive for quality and would like to make sure that every language scanned behaves as expected with ARM64.

Anyway It is super cool to know that it works on your case!

please note that this is not officially supported, therefore you will not get support out of it.

**Comment by mkarwin** [comment]
> Hello everyone, this is a recurring topic that is raised as issues.
> 
> The ARM64 for [sonar-scanner-cli-docker](https://sonarsource.atlassian.net/browse/SONAR-scanner-cli-docker) is an ongoing topic that we are pushing for. Nonetheless, it requires a huge validation as we thrive for quality and would like to make sure that every language scanned behaves as expected with ARM64.
> 
> Anyway It is super cool to know that it works on your case!
> 
> please note that this is not officially supported, therefore you will not get support out of it.

Since we know docker image for ARM with the CLI can be built using buildx (as used by the referenced github action) and the only thing stopping you from doing so is the validation step, can you release it with an asterisk/proviso which languages have already been verified and which are still not validated? My guess is the C/C++/C# family may not be fully supported/validated due to those requiring build-wrapper be used which is X86_64-only, but maybe you actually do not need to restrict CLI to x86 as merely requiring build-wrapper output would be sufficient? Or maybe build-wrapper could be offered in an ARM variant as well?
Best option, you could add tests to QA steps to verify CLI in an image works as expected. Then running the test against X86 platform image and ARM one could easily pinpoint not supported languages and auto-populate that info as a simple table in readme markdown document.

**Comment by RodrigoDornelles** [comment]
In terms of validating the tool itself, you shouldn't have any problems as it is written in Java, which has its own runtime.

Now it's a matter of **C**, **C++** wrappers...etc, perhaps partial support so as not to impede the analysis of other languages such as **nodejs**, **kotlin**, **java**, **flutter**... I think it wouldn't be that much of a problem to cause an error as support is not yet complete .

I'm currently working on migrating some pipelines from x86 to ARM, the company I work for is experimenting with ARM on the backend and is having good results.

ARM is no longer just Raspberry-Pi and Smartphones, servers and super-computers have been in the business world for a long time.

----------------------------------
@jCOTINEAU @mkarwin

**Comment by YasserAntonio** [comment]
just to let you know that builded sonar-cli using the official reopen a rasp4 without any trouble : https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/DEVELOPER.md
