### ISSUE TITLE
While running the sonar scanner on a container encountering an issue

### ISSUE THREAD

**Issue by ar-srinivas** [SonarSource/sonar-scanner-cli-docker#207]
While running the sonar-scanner CLI command, facing the below issue.

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
16:14:12.022 DEBUG: Request {"id":"443206795","jsonrpc":"2.0","method":"exit"}
16:14:12.026 DEBUG: Failed cs exiteslint
java.lang.reflect.UndeclaredThrowableException: null
        at jdk.proxy11/jdk.proxy11.$Proxy68.exit(Unknown Source)

**We are using this infra:**
INFO: SonarScanner 5.0.1.3006
INFO: Java 17.0.9 Eclipse Adoptium (64-bit)
INFO: Linux 5.10.192-183.736.amzn2.aarch64 aarch64
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Analyzing on SonarQube server 9.9.0.65466

Anyone has seen this issue or is there any suggestion to resolve this issue?

**Comment by carminevassallo** [comment]
Dear @ar-srinivas,

Thanks for reporting this issue! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

Could you please post your issue there? In the meantime, I'm closing it.
