### ISSUE TITLE
"ssh: not found" error while using cli-image with jenkins

### ISSUE THREAD

**Issue by Segate-ekb** [SonarSource/sonar-scanner-cli-docker#208]
**Error description:**
When using the latest docker images of sonarsource/sonar-scanner-cli (Tags 5.4, latest), in conjunction with Jenkins, an error occurs when trying to use an SSH connection to a git repository. This is because the image does not contain SSH.

**Logs:**

```
14:08:16  ERROR: Error cloning remote repo 'origin'
 14:08:16  hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress -- ssh://git@git.galamart.dev:8922/1c/monitoring.git +refs/heads/develop:refs/remotes/origin/develop" returned status code 128: 
 14:08:16  stdout:  
 14:08:16  stderr: /tmp/workspace/monitoring_QA_develop@tmp/jenkins-gitclient-ssh10976168166800589519.sh-copy: line 6: ssh: not found 
 14:08:16  fatal: Could not read from remote repository.
```

**Workaround:**
Add "apk add openssh" to the docker image launch command.

This issue does not exist in the current master branch, as the base image has been changed.

**Comment by carminevassallo** [comment]
Dear @Segate-ekb,

Thanks for reporting this issue! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

Could you please post your issue there? In the meantime, I'm closing it.
