### ISSUE TITLE
Wrong cacerts path in entrypoint.sh ?

### ISSUE THREAD

**Issue by nvierge** [SonarSource/sonar-scanner-cli-docker#210]
Hello,

When certificates are present in `/tmp/cacerts`, they are imported via keytool into the entrypoint.sh script.
The path to the key store doesn't seem to be up to date, probably since the base image was changed.
In the eclipse-temurin:17-jre image, the path to cacerts is `/opt/java/openjdk/lib/security/cacerts` (instead of `/usr/lib/jvm/default-jvm/jre/lib/security/cacerts`).

In addition, the default user is now scanner-cli.
I'm not sure he has sufficient rights to run keytool properly.

**Comment by carminevassallo** [comment]
Hey @nvierge, thanks a lot for raising this issue. We are tackling it here #214 :)

To help us with handling issues or feature requests, feel free to consider posting in our [community forum](https://community.sonarsource.com/) next time!
