### ISSUE TITLE
add: github container registry and aws public registry

### ISSUE THREAD

**Issue by ohbus** [SonarSource/sonar-scanner-cli-docker#212]
Please additionally publish the images to 
- [Public ECR](https://gallery.ecr.aws/) 
- [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)

**Comment by carminevassallo** [comment]
Hi @ohbus,

thanks for your suggestions. Could you please tell us more about your needs in that regard? Why do you need to have the sonar-scanner docker image available in those two registries? Which limitations are you currently facing when pulling from DockerHub directly? Having your perspective can help us evaluate your request :)

**Comment by ohbus** [comment]
Simply put 
- [GHCR](https://ghcr.io/) combines code and container images, making it convenient for developers who use GitHub for version control and deploy and maintain the packages and release software.
- [AWS ECR](https://public.ecr.aws/) shines for container-based workloads running on AWS, especially for continuous deployments within the AWS environment. 

Both the environment shines and are more popularly used than other public container registries as DockerHub rate limits pull, so when CI jobs/workflows are running to use the image it often hits the ceiling when working in an org where build servers are on-prem.

There are multiple ways to have a workaround, but having them in other public registries such as AWS ECR and GHCR would surely help.

**Comment by carminevassallo** [comment]
Hi @ohbus,

Thanks for clarifying your needs. Based on your and other comments, the pull-rate-limits issue seems to be the most important point to address. It should be solved once we release our sonar-scanner image as an official one. We are working on that.

I invite you to post this suggestion on our [community forum](https://community.sonarsource.com/). There, PMs will evaluate your request and provide more info.
