### ISSUE TITLE
Please push sonarsource/sonar-scanner-cli to Dockerhub to get the latest base eclipse-temurin:17-jre

### ISSUE THREAD

**Issue by vladimir-kouznetsov** [SonarSource/sonar-scanner-cli-docker#213]
Could you please push (rebuild) sonarsource/sonar-scanner-cli to Dockerhub 
to get the latest base eclipse-temurin:17-jre with the latest OS,
where eclipse-temurin:17-jre switched from outdated Alpine 15 to the lasted Ubuntu 22.04 ?

**Comment by carminevassallo** [comment]
Hi @vladimir-kouznetsov,

we are still testing the compatibility of the new image with all our analyzers before releasing it. 

Feel free to reach out to us in our [community forum](https://community.sonarsource.com/). There, PMs will evaluate your request and provide more info.
