### ISSUE TITLE
Wrong cacerts path in entrypoint.sh

### ISSUE THREAD

**Issue by nvierge** [SonarSource/sonar-scanner-cli-docker#218]
Hello,

The base image is no longer eclipse-temurin:17-jre.
 The path to cacerts is /usr/lib/jvm/default-jvm/jre/lib/security/cacerts (instead of /opt/java/openjdk/lib/security/cacerts) in entrypoint.sh.
This path depends on the base image you use.
See https://github.com/SonarSource/sonar-scanner-cli-docker/issues/210.

Will you use eclipse-temurin:17-jre or alpine:3.19 ?

**Comment by csaba-feher-sonarsource** [comment]
Hi,
 @nvierge we are planning to use alpine:3.19

**Comment by pierre-guillot-gh** [comment]
Hey @nvierge, thanks for reporting this (again). It's now fixed with https://github.com/SonarSource/sonar-scanner-cli-docker/pull/219

**Comment by pierre-guillot-gh** [comment]
> Will you use eclipse-temurin:17-jre or alpine:3.19 ?

We might have overlooked something here. Let me circle back on this with the team.

**Comment by pierre-guillot-gh** [comment]
Okay, I was missing some information. We moved to Temurin for Arm64 support, but in the meantime, Alpine support for Arm64 was released, so we are switching back to Alpine. So we are staying on Alpine.

**Comment by nvierge** [comment]
Thank you for the information.
