### ISSUE TITLE
Removal of curl from the base image

### ISSUE THREAD

**Issue by nextrevision** [SonarSource/sonar-scanner-cli-docker#225]
It seems that in #217 curl was removed along with python libraries. Was that intentional? @gaiazov also noted this in that MR (https://github.com/SonarSource/sonar-scanner-cli-docker/pull/217#pullrequestreview-2004063505), but I wanted to bring it up here for visbility.

Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by henryju** [comment]
Hi, this is intended, as the scanner doesn't need curl itself, so we are trying to decrease the attack surface of our images.

If you need it for your own purposes, feel free to extend our image to add it back.
