### ISSUE TITLE
Add compatibility nodes to documentation

### ISSUE THREAD

**Issue by ericsmalling** [SonarSource/sonar-scanner-cli-docker#246]
It is unclear what releases on this image are in active support and which server versions are supported by each of them.

For example, as of now, it appears that both 5.01 and 4.8.1 are both supported (both released nearly simultaneously) but are they? Do they have different sets of SonarQube they are compatible with?  etc

**Comment by henryju** [comment]
Hi @ericsmalling we are not actively watching the GitHub issues, and I am about to close them. Please use our [community forum ](https://community.sonarsource.com/)to raise issues, ask questions or ask for new features.

Regarding your question, as far as I know, we are only supporting the latest release of all our scanners.

**Comment by ericsmalling** [comment]
What category do I use?  There's none for the scanner-cli project or docker image of it.

**Comment by ericsmalling** [comment]
opened https://community.sonarsource.com/t/add-compatibility-notes-to-sonar-scanner-cli-readme-docs/115778
