### ISSUE TITLE
SONAR_HOST_URL did not work

### ISSUE THREAD

**Issue by mindfocus** [SonarSource/sonar-scanner-cli-docker#25]
run:
`
docker run -e SONAR_TOKEN=token_private -e SONAR_HOST_URL=http://private.server.address -it -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
`
result:
<pre>
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /usr/src/sonar-project.properties
INFO: SonarQube Scanner 4.1.0.1829
INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
INFO: Linux 5.0.0-27-generic amd64
INFO: User cache: /home/scanner-cli/.sonar/cache
ERROR: SonarQube server [http://localhost:9000] can not be reached
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.246s
INFO: Final Memory: 2M/20M
INFO: ------------------------------------------------------------------------
</pre>
info:
sonarsource/sonar-scanner-cli:latest

**Comment by jacek-poreda-sonarsource** [comment]
> INFO: SonarQube Scanner 4.1.0.1829

Could you please try with newer docker image? It seems you use 4.1 and this variable is available from version 4.2.

**Comment by mindfocus** [comment]
that works!  my mistake, thanks
