### ISSUE TITLE
Document how to create my own docker (with cache)

### ISSUE THREAD

**Issue by lenntt** [SonarSource/sonar-scanner-cli-docker#27]
As my CI is dockerized and works with clean workspaces every build,
I'd like to create wrap this into my own with the cache (the .jar, the plugins) to save me several minutes every build.

I think there's a general usecase here, so documentation around a good practice to do so would be really helpful.

**Comment by lenntt** [comment]
Ideally, (for my use case) I'd get an understanding of how I can build my own image with a version of the cache built into the image (which might not be _best_ practice, but all state in my CI is very volatile, my options to reuse cache folders are very limited).

Is there a chance this use case is supported/added to these docs?

**Comment by kav** [comment]
Just a shot here but how about
```Dockerfile
FROM sonarsource/sonar-scanner-cli:4.2
ENV SONAR_HOST_URL <Your host url>
ENV SONAR_TOKEN <Your token>
# the rest of the environment you want for the sonarqube
... 
# copy some basic config that keeps it from failing but doesn't take space in the images
COPY  sonar-project.properties /usr/src/sonar-project.properties 
RUN /usr/bin/entrypoint.sh
```
That should create a layer that has connected to your server and cached all the relevant bits.

**Comment by lenntt** [comment]
Thanks, closing this as I managed to do it in a similar fashion.

**Comment by marcellodesales** [comment]
@kav How to cache plugins while building the Docker image for specific languages, instead of downloading all plugins listed by api/plugins/installed??? Docker images are very specific to the project running the scanner...
