### ISSUE TITLE
"Unknown flag: chown" when building docker image. 

### ISSUE THREAD

**Issue by Keuthonymous** [SonarSource/sonar-scanner-cli-docker#29]
Not sure what the cause is. I'm pretty novice when it comes to docker. I did find a work around though. 

installing sudo and changing `COPY --chown=scanner-cli:scanner-cli bin /usr/bin/` 

to

`COPY . bin /usr/bin
RUN sudo chown -R scanner-cli:scanner-cli /usr/bin/`

seems to have addressed my issue. Hope it helps someone.

**Comment by CCFenner** [comment]
Is your Docker version below `17.09`? 

> COPY –-chown flag implemented in Docker 17.09 and above with the exception of Docker EE 2.0. 

See also [here](https://success.docker.com/article/workaround-for-unsupported-dockerfile-copy-chown-flag).
