### ISSUE TITLE
cannot set projectKey

### ISSUE THREAD

**Issue by mhow2** [SonarSource/sonar-scanner-cli-docker#33]
In the current implementation, I don't see I'm supposed to set the `projectKey` or other variables I might need... ?

**Comment by kav** [comment]
Use a sonar-project.properties file in the same directory as your source code. It will be linked by the `-v "$(pwd):/usr/src"` which mounts the current directory in the container. See https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

**Comment by sebhoss** [comment]
I've used `--entrypoint` to overwrite the existing one and use it like this:

```
docker run \
    --rm
    --user="$(id -u):$(id -g)" \
    --entrypoint /opt/sonar-scanner/bin/sonar-scanner \
    sonarsource/sonar-scanner-cli:latest \
        -Dsonar.projectBaseDir=/usr/src \
        -Dsonar.branch.name='some-branch' \
        -Dsonar.login=... \
        -Dsonar.host.url=...
```
