### ISSUE TITLE
Interface needs to allow passing all properties on docker run command line

### ISSUE THREAD

**Issue by davidmichaelkarr** [SonarSource/sonar-scanner-cli-docker#34]
The interface to this seems to be very inflexible.  I need to be able to specify on the "docker run" command line all the possible properties that I could pass to sonar-scanner.  It's not useful to make it look for a properties file.  Allow sending all properties on the command line.

**Comment by kav** [comment]
Also would be nice to not require environment variables for existing properties (e.g. the sonarqube host url can be read from sonar-project or sonar-scanner properties files)

**Comment by michal-duda-sonarsource** [comment]
This has been added to version 4.4 image.
