### ISSUE TITLE
Some results from quality tools (as valgrind) are not taken in account using the option -v "$(pwd):/usr/src" 

### ISSUE THREAD

**Issue by Tom3592** [SonarSource/sonar-scanner-cli-docker#37]
The generic command to run the docker container is OK in general:
```
docker run -e SONAR_HOST_URL=http://foo.acme:9000 -it -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
```

But here is drawback using tools which output files might contain complete full paths.
Example with Valgrind:

## Source code

#include <iostream>
```

int main(int argc, const char* argv[]) {

    std::cout << "Hello World !" << std::endl;
    int* ptr = new int [10000]; // hello valgrind or DrMemory !
    return 0;
}
```

### Compilation and Valgrind execution

```
 g++ -o test -g HelloWorld.cpp 
 valgrind --xml=yes --xml-file=report.xml ./test
```

### Valgrind XML file

Note the full pathnames (eg _/home/user/HelloWorld_) 
```
    <frame>
      <ip>0x4C298A8</ip>
      <obj>/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>operator new[](unsigned long)</fn>
      <dir>/builddir/build/BUILD/valgrind-3.11.0/coregrind/m_replacemalloc</dir>
      <file>vg_replace_malloc.c</file>
      <line>423</line>
    </frame>
    <frame>
      <ip>0x4008F1</ip>
      <obj>/home/user/HelloWorld/test</obj>
      <fn>main</fn>
      <dir>/home/user/HelloWorld</dir>
      <file>HelloWorld.cpp</file>
      <line>6</line>

```

The output shows that SonarQube is not able to retrieve the code sources  
```
 docker run --network="host" -e SONAR_HOST_URL=http://localhost:9000 --user="$(id -u):$(id -g)" -it -v "$PWD:/usr/src" sonarsource/sonar-scanner-cli


INFO: Sensor C++ (Community) ValgrindSensor [cxx]
INFO: Searching reports by relative path with basedir '/usr/src' and search prop 'sonar.cxx.valgrind.reportPath'
INFO: Parser will parse '1' report file(s)
INFO: Processing report '/usr/src/report.xml'
WARN: Cannot find a project file to assign the valgrind error 'ValgrindError [kind=Leak_DefinitelyLost, text=40,000 bytes in 1 blocks are definitely lost in loss record 1 of 1, stacks=[ ValgrindStack=[0x4C298A8: operator new[](unsigned long) (vg_replace_malloc.c:423)
0x4008F1: main (HelloWorld.cpp:6)] ] ]' to
INFO: CXX-VALGRIND processed = 0
INFO: Sensor C++ (Community) ValgrindSensor [cxx] (done) | time=79ms
```

This is due (I think !) to the mapping of 

_/home/user/HelloWorld_  in the Valgrind XML file does not exist under _/usr/src_ directory mounted in the docker container.

Thank you for this little analysis and any workaround.

**Comment by Tom3592** [comment]
My configuration:
SonarQube 7.9.1
cxx plugin community 1.3.1
valgrind-3.11.0
latest sonar-scanner image from https://hub.docker.com/r/sonarsource/sonar-scanner-cli

**Comment by konstruktoid** [comment]
what if you add `-v /home/user/HelloWorld:/home/user/HelloWorld`?

**Comment by prunier** [comment]
Hello (sorry for the delay)
yes good idea but it seems that /usr/src is needed by sonar-scanner:

`java.lang.IllegalStateException: Unable to create user cache: /usr/src/.sonar/cache`

**Comment by tobias-trabelsi-sonarsource** [comment]
Hello everyone :wave: 

this thread is rather old and seems to concern a cpp project, which is not ment to be analyzed with the sonar-scanner-cli docker image as stated in the [Readme](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/README.md).
you can find additional information about that here: https://docs.sonarqube.org/latest/analysis/languages/cfamily/

feel free to create a new thread in our [community forum](https://community.sonarsource.com/) if you have additional questions

**Comment by prunier** [comment]
you're right. Sorry no having taken in account the Readme
