### ISSUE TITLE
Support shell sensor

### ISSUE THREAD

**Issue by acemoo** [SonarSource/sonar-scanner-cli-docker#39]
Currently we are getting these errors.
`INFO: Sensor ShellCheck Sensor [shellcheck]
 ERROR: Error executing command: Cannot run program "shellcheck": error=2, No such file or directory
 ERROR: Is the command installed and in the path?
 ERROR: Hint: run the scanner in debug mode to get the complete stack trace
 INFO: Sensor ShellCheck Sensor [shellcheck] (done) | time=6ms
 `

Please install spellcheck to allow scanning of shell scripts.

**Comment by michal-duda-sonarsource** [comment]
Added in 4002282afd93081553fddd5fed71287f69f3d985.
