### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by kav** [SonarSource/sonar-scanner-cli-docker#41]
#14  #31, #36 all lay out sensible changes to fix the same set of underlying issues and have been hanging around for a while. Any chance of those getting merged?

**Comment by konstruktoid** [comment]
And #42.
It will get messy cheery-picking, rebasing and merging soon.

**Comment by pierre-guillot-sonarsource** [comment]
Hi, a misconfiguration on our side made us not notified of opened PR in the repo :shame:

**Comment by kav** [comment]
Any plan to merge any/all of those?

**Comment by pierre-guillot-sonarsource** [comment]
There is an open task on our side to spend time on this image. Unfortunately, everybody is busy right now (for example with this docker related subject: https://jira.sonarsource.com/browse/MMF-1931)
