### ISSUE TITLE
Entrypoint.sh overrides properties set elsewhere

### ISSUE THREAD

**Issue by kav** [SonarSource/sonar-scanner-cli-docker#48]
I can't use any standard sonarqube config mechanism (config files or command line options) for any of the properties found in the entrypoint as it overrides them all. As such, like everyone else PRing here, I've had to override entrypoint on runs.

**Comment by michal-duda-sonarsource** [comment]
Can you provide more details? The entrypoint differs a bit between versions. Which version are you trying to run and which specific properties do you have in mind?

**Comment by michal-duda-sonarsource** [comment]
See my comment here: https://github.com/SonarSource/sonar-scanner-cli-docker/issues/26#issuecomment-654927589
