### ISSUE TITLE
Integration with Gitlab

### ISSUE THREAD

**Issue by kirill-konshin** [SonarSource/sonar-scanner-cli-docker#51]
I tried to set up SonarScanner CLI according to the documentation https://docs.sonarqube.org/latest/analysis/gitlab-cicd/ but in my case scanner becomes stuck at some point:

```
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /builds/xxx/sonar-project.properties
INFO: SonarScanner 4.3.0.2102
INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
INFO: Linux 3.10.0-1062.1.1.el7.x86_64 amd64
INFO: User cache: /builds/xxx/.sonar/cache
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /builds/xxx/sonar-project.properties
INFO: Analyzing on SonarQube server 8.2.0
INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=1730ms
INFO: Server id: XXX
INFO: User cache: /builds/xxx/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=326ms
```

It is consistent and all pipelines eventually die because of timeout, normally scanner was able to finish in 5-10 minutes.

**Comment by michal-duda-sonarsource** [comment]
Looks like the scan timeouts on downloading the plugins, which takes more time than the step that finished last (downloading just the index) but it shouldn't take very long anyway. Are you using self-managed or cloud GitLab? You also mentioned that `normally scanner was able to finish in 5-10 minutes`- is there anything that was changed in your setup before the issue started to appear?

**Comment by kirill-konshin** [comment]
Issue started to appear once I switched to the docker image from above mentioned link. My own docker image works well: https://github.com/ringcentral-docker/web-tools/blob/master/13-alpine/Dockerfile

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @kirill-konshin ,

this is a rather old issue. If you are still facing this, please open a new thread in our [community forum](https://community.sonarsource.com/)
