### ISSUE TITLE
Docker image build is failing in GitHub actions

### ISSUE THREAD

**Issue by soham308** [SonarSource/sonar-scanner-cli-docker#60]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [ ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

![image](https://user-images.githubusercontent.com/46596703/82981814-761dc100-a00a-11ea-97a9-371f3ff5dba2.png)

**Comment by michal-duda-sonarsource** [comment]
This was a temporary server problem, everything should be ok now.
