### ISSUE TITLE
Reopening issue #60 Docker image problem still happening. 

### ISSUE THREAD

**Issue by soham308** [SonarSource/sonar-scanner-cli-docker#62]
Please ensure your issue adheres to the following guidelines: 
- [ ] Please check the problem is not already reported
- [ ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

https://github.com/SonarSource/sonar-scanner-cli-docker/issues/60

**Comment by michal-duda-sonarsource** [comment]
Another server issue, should be good now.
