### ISSUE TITLE
Environment variable SONAR_TOKEN deprecated?

### ISSUE THREAD

**Issue by wsl-service** [SonarSource/sonar-scanner-cli-docker#64]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by opsline-josiecki** [comment]
```
docker run -e SONAR_HOST_URL=https://sonar.slytrunk.com -e SONAR_TOKEN=$SONAR_TOKEN --user="$(id -u):$(id -g)" -it -v "$PWD:/usr/src" sonarsource/sonar-scanner-cli
```
Returns 
```
ERROR: Error during SonarScanner execution
ERROR: Not authorized. Analyzing this project requires to be authenticated. Please provide the values of the properties sonar.login and sonar.password.
ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

while 

```
docker run -e SONAR_HOST_URL=https://sonar.slytrunk.com -e SONAR_LOGIN=$SONAR_TOKEN --user="$(id -u):$(id -g)" -it -v "$PWD:/usr/src" sonarsource/sonar-scanner-cli
```
Authenticates.

Docs here https://docs.sonarqube.org/latest/user-guide/user-token/ instruct users to do the following when using a token in the properties:
```
when running analyses on your code: replace your login by the token in the sonar.login property
```

**Comment by CCFenner** [comment]
[Looks](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/bin/entrypoint.sh#L24) like `SONAR_LOGIN` should work..

**Comment by opsline-josiecki** [comment]
Thanks @CCFenner , I'm not sure what was wrong with my setup but I'll close the ticket
