### ISSUE TITLE
Use NodeJS 12

### ISSUE THREAD

**Issue by CCFenner** [SonarSource/sonar-scanner-cli-docker#66]
Are there plans to switch to the current NodeJS LTS soon? See https://nodejs.org/en/about/releases/

**Comment by michal-duda-sonarsource** [comment]
Indeed, the bundled version is quite outdated. We will upgrade to version 14 since it's the active one and it's supported by the language plugins.

**Comment by michal-duda-sonarsource** [comment]
I jumped the gun on this one, we have to revert this change for now due to compatibility issues. I'm reopening this issue and we will revisit this after releasing version 4.4

**Comment by saberduck** [comment]
done in https://github.com/SonarSource/sonar-scanner-cli-docker/pull/81

**Comment by CCFenner** [comment]
When will this be available on Docker Hub?

**Comment by CCFenner** [comment]
@saberduck

**Comment by michal-duda-sonarsource** [comment]
We don't have specific plans yet. The next version of the scanner will probably be released when our [DockerHub official library submission PR](https://github.com/docker-library/official-images/pull/8100) is reviewed but if it takes too long we might release something sooner. We are currently busy with other features though.

**Comment by CCFenner** [comment]
Closing as `sonarsource/sonar-scanner-cli:4.5` now comes with Node `v12.18.2`.
