### ISSUE TITLE
Use Typescript 3.8+

### ISSUE THREAD

**Issue by avindra** [SonarSource/sonar-scanner-cli-docker#67]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports

The 3.8 release adds support for syntax such as:

```ts
import type {SomeType} from 'package'
```

Sonar fails to process these kinds of files with the following error:

```
ERROR: Failed to parse file [src/code.ts] at line 5: '=' expected.
```

**Comment by michal-duda-sonarsource** [comment]
Typescript 3.8.0 is not supported by [SonarTS](https://docs.sonarqube.org/latest/analysis/languages/typescript/) yet. Feel free to open a thread regarding TS 3.8.x and SonarTS on the [community forum](https://community.sonarsource.com/).
