### ISSUE TITLE
SONAR_PROJECT_BASE_DIR not working as expected

### ISSUE THREAD

**Issue by jcoelho93** [SonarSource/sonar-scanner-cli-docker#71]
Due to some project requirements I cannot mount my project in `/usr/src` so I mounted it in `/projectName/src` and set `SONAR_PROJECT_BASE_DIR` to `/projectName/src`

When I run the sonar-scanner-cli-docker image it cannot find the `sonar-project.properties` in the `/projectName/src` folder.

```sh
> docker run --rm -it -e SONAR_TOKEN=$SONAR_TOKEN -e SONAR_HOST_URL=$SONAR_HOST_URL -e SONAR_PROJECT_BASE_DIR=/projectName/src --user="$(id -u):$(id -g)" -v /host/path/projectName:/projectName sonarsource/sonar-scanner-cli:latest
```

If I add a single character to the end of the command, let's say **c**:

```sh
> docker run --rm -it -e SONAR_TOKEN=$SONAR_TOKEN -e SONAR_HOST_URL=$SONAR_HOST_URL -e SONAR_PROJECT_BASE_DIR=/projectName/src --user="$(id -u):$(id -g)" -v /host/path/projectName:/projectName sonarsource/sonar-scanner-cli:latest c
```
it then finds the `/projectName/src/sonar-project.properties` but then tries to create a `?` directory in `/usr/src` and fails. Very weird error...

`/projectName/src/sonar-project.properties`:
```
sonar.inclusions=**/*.cpp,**/*.c,**/*.cxx,**/*.h
sonar.projectKey=projectName
sonar.language=c++
sonar.sources=.
sonar.cxx.coverage.reportPath=coverage-report.xml
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
```

**Comment by malcolm061990** [comment]
Hi. I used that command and it works:
```
docker run --rm -v "PATH_TO_PROJECT:/fastapi" sonarsource/sonar-scanner-cli \
	-Dsonar.projectBaseDir="/fastapi" \
	-Dsonar.projectKey=PROJECT_KEY \
	-Dsonar.host.url=SONAR_URL \
	-Dsonar.login=SONAR_LOGIN
```

**Comment by derhecht** [comment]
Tried setup Docker working dir with
docker run .... -w /projectName/src ...
also?

Or at least, use
-Dsonar.projectBaseDir="/projectName/src"
as mentioned by @malcolm061990

**Comment by tobias-trabelsi-sonarsource** [comment]
Hello there,

this seems to be a cpp project, which as stated in the readme of this repository is not supported to be analyzed within a docker image. you can find more information about that here: https://docs.sonarqube.org/latest/analysis/languages/cfamily/

if you are still facing issues in your setup, feel free to create a new thread in our [community forum](https://community.sonarsource.com/)
