### ISSUE TITLE
Configuration of scanner CLI

### ISSUE THREAD

**Issue by simonbrandhof** [SonarSource/sonar-scanner-cli-docker#8]
Environment variables should be used to set properties as CLI arguments. For instance `-e SONAR_PROJECT_KEY=foo -e SONAR_ORGANIZATION=bar` are converted to `-Dsonar.projectKey=http://foo -Dsonar.organization=bar` when running `sonar-scanner`.

This mechanism brings the support of Docker secrets.

**Comment by simonbrandhof** [comment]
The value of this improvement is decreased since the native support of SONAR_HOST_URL in scanners, in addition to SONAR_TOKEN:
- scanner for Maven: https://jira.sonarsource.com/browse/MSONAR-172
- scanner for Gradle: https://jira.sonarsource.com/browse/SONARGRADL-66
- scanner CLI: https://jira.sonarsource.com/browse/SQSCANNER-63
- scanner for Ant: https://jira.sonarsource.com/browse/ANTTASK-59

As a consequence the feature suggested in this ticket should apply only to the other parameters listed here: https://docs.sonarqube.org/latest/analysis/analysis-parameters/

**Comment by sns-seb** [comment]
Hi @simonbrandhof : good point. However, this image bundles only scanner-cli (not any of the other scanners) and in this scanner, `SONAR_HOST_URL` and `SONAR_TOKEN` are only supported starting 4.2.

We currently bundle 4.1.

**Comment by simonbrandhof** [comment]
so everything is on track to not support SONAR_HOST_URL in this image!

**Comment by sns-seb** [comment]
This PR applied to 4.1 and could be applied as is.

The explicit support of `SONAR_HOST_URL` in the image can be removed when bundled version is upgraded to 4.2. WDYT?

**Comment by simonbrandhof** [comment]
It does not sound a good idea to me:
- this is a development for an image that is not used at all yet. 
- release 4.2 will be announced in the next few days (or even today?)
- the pull is not approved yet
- validation takes time

**Comment by sns-seb** [comment]
What do you refer to by `the pull is not approved yet`?

**Comment by simonbrandhof** [comment]
I edited my comment, `request` was missing.
