### ISSUE TITLE
Add environment variable so sonar.projectKey can be passed at docker execution level

### ISSUE THREAD

**Issue by vchan2002** [SonarSource/sonar-scanner-cli-docker#83]
Just another option on the table to pass the sonar.projectkey at runtime rather than having sonar-project.properties at the project level.  Will submit a PR in a day or two.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hey @vchan2002 ,
the scanner does not support environment variables on the application level currently and your PR would basically implement a feature that is already there
```
docker run \ 
    --rm \
    -e SONAR_HOST_URL="http://${SONARQUBE_URL}" \
    -v "${YOUR_REPO}:/usr/src" \
    sonarsource/sonar-scanner-cli \
  -Dsonar.projectKey=${YOUR_PROJECT_KEY} \
  -Dsonar.login=${YOUR_TOKEN} 
```
can you make use of this or elaborate why this is not working for you?

**Comment by derhecht** [comment]
@tobias-trabelsi-sonarsource right. but why do you have made SONAR_PROJECT_BASE_DIR and login stuff provided as Docker environment variables then?

**Comment by tobias-trabelsi-sonarsource** [comment]
@derhecht because these are required parameters in order to have the scanner working and should not be put to a `sonar-project.properties` file as you probably don't want to push your access key to your scm

**Comment by derhecht** [comment]
ok, regarding login I got it. but SONAR_PROJECT_BASE_DIR is not and maybe even also filled with environment variables from CI used.

**Comment by tobias-trabelsi-sonarsource** [comment]
the `SONAR_PROJECT_BASE_DIR` is something specific when running within a containerized environment as it should point to the path of the project within the container, so it is highly depended on the volume mount in the docker run command that is used. 
the projektKey is something you define within sonarqube/sonarcloud so something completely independent from the environment where the scanner is running in

**Comment by vchan2002** [comment]
I understand that, if a sonar-project.properties is there, or if I add that as a java environment variable, rather as a docker variable, it should work too.  However, I'm just looking for additional ways to onboard sonarqube usage for our repos and teams ATM.  I'd like to think that there will be use cases and this will be a positive contribution.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @vchan2002 

i think i understand where you are coming from but as you already noted we are currently just simulating the availability to configure the scanner via environment variables for the bare minimum. there is a chance that the scanner will support the configuration via environment variables in the future but until then i would not advise to increase the complexity (even slightly) by introducing a new way of wrapping a parameter.

i hope that you can understand my reasoning and work around this as i described [here](https://github.com/SonarSource/sonar-scanner-cli-docker/issues/83#issuecomment-668590735)  

btw: we have a [community forum](https://community.sonarsource.com/) where you can request a new feature, get help or just discuss everything sonar related. maybe this would be a better starting point next time as we monitor this closer as the github issues (: 

have a good day and thank you again for investing the time to create a PR
