### ISSUE TITLE
Alternative tag for nightly builds?

### ISSUE THREAD

**Issue by j0nm1** [SonarSource/sonar-scanner-cli-docker#85]
Is it possible to provide an alternative channel (tag) to the automatic nightly builds? Like so:
```
sonarsource/sonar-scanner-cli:4.4
sonarsource/sonar-scanner-cli:4.4-nightly
```
So that the normal image is only rebuilt when there are new commits?

**Why would this be useful?**
We are using [renovate](https://github.com/renovatebot/renovate) to keep our dependencies up to date and pin the SHAs of the used docker images to see when things change. The nightly build leads to a different SHA every day and `renovate` creates a merge request to update it - this creates a lot of unnecessary noise in our projects.

Is there are any reason against using a separate tag?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hey @j0nm1 ,
the long term plan is to have this as a official image and then this will not be relevant anymore, but this is a little bit stuck currently. we are in clarification if we can expect to have an official image in the near future or if this is not the case we will rework the release to always push to `latest` and have the version tag only rebuild if there are vulnerabilities in the image. i think this is a cleaner solution then to have a new tag for this

hope you understand and i will come back to you when we have clarified this

**Comment by malena-ebert-sonarsource** [comment]
Hi @j0nm1,

the build pipeline was improved. A new image will be pushed to docker hub on changes only.
This should fix your issue.
