### ISSUE TITLE
preinit plugin cache

### ISSUE THREAD

**Issue by CCFenner** [SonarSource/sonar-scanner-cli-docker#94]
Running the first scan with `sonarsource/sonar-scanner-cli:4.5` the plugin cache is not filled, which takes about 25 seconds:

```log
...
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=103ms
INFO: Load/download plugins (done) | time=26282ms
INFO: Loaded core extensions: developer-scanner
INFO: Process project properties
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 31.272s
INFO: Final Memory: 6M/27M
```

All further calls leverage the plugin cache:

```log
...
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=93ms
INFO: Load/download plugins (done) | time=202ms
INFO: Loaded core extensions: developer-scanner
INFO: Process project properties
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2.272s
INFO: Final Memory: 6M/27M
```

It would be nice if the image comes with a pre-filled cache to speed up ramp-up-time and save bandwidth.

**Comment by mark-rekveld-sonarsource** [comment]
Thanks for your suggestion. The cache is loaded from the SonarQube. and/or SonarCloud instance. And there is no means at the moment to guarantee that the cache will be identical between SonarQube instances. This because it also depends on languages installed and possible other plugins.

I'll give it some though and talk with the team to see if there is any way of doing this.

**Comment by CCFenner** [comment]
Thanks.

We currently consider building an own image based on `sonarsource/sonar-scanner-cli:4.5` with a prefilled cache directly for our instance as we cannot have a persistent volume for the cache.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi here,

i have created [DOCKER-4](https://jira.sonarsource.com/browse) to track this and will close this GH issue for now

**Comment by marcellodesales** [comment]
Hi @CCFenner @tobias-trabelsi-sonarsource @mark-rekveld-sonarsource  is there any way to limit the plugins that gets downloaded every time? 

What I'm looking for is something in the lines of https://github.com/SonarSource/sonar-scanner-cli-docker/issues/27#issuecomment-577608354, where we can create our own Docker images, pointing to our Sonarqube server, and limit/cache the plugins installed per project: one in java, others nodejs, others C and C++, others in Golang, others in Terraform... why downloading all of them when it's not needed?
